# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05de46f0068c9d522648a9d111635215ea3e4b0e86818205aecee47c836c4c6fc379722c46ce378b5f43402ae07008ff353c041bef5dbe9efc3c26b77b9b0e8a

test:
  secret_key_base: a48f8d7bb7b1e9989d7675b63664457707aa55af5a752d176870381e3ae3812cd76a0ccf32c4a4e0aa4a427ebd14062d13685058ba32c0a2d9f00994c164c392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
